### DISCUSSION TITLE
Welcome to tjahzi Discussions!

### DISCUSSION THREAD

**Discussion by tkowalcz** [tkowalcz/tjahzi#12] [General]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by silasmue** [comment]
Hi, I am experimenting with your plugin and everything works fine. I added markers to the config according to the log4j docs and after that I receive weird NullPointer Exceptions. Are markers supported because I cannot find something in the documentation about it?

**Reply by silasmue** [reply]
Nevermind. 
You can use markers and make them to labels in Loki.
```
Label:
    - name: Logger
      pattern: "%logger"
    - name: Marker
      pattern: "%marker"
LogLevelLabel: log_level
```
If you add that to the log4j.yaml
